### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by YaibaToKen** [games647/mcMMOExtras#10]
Hey, so I'm not sure whether it's something I forgot to configure or if it's something wrong with the plugin, either way, I figured I'd open an issue :) 

```
[18:49:18 WARN]: [McMMOExtras] Task #3694 for McMMOExtras v5.2.2 generated an exception
java.lang.NullPointerException
	at net.milkbowl.vault.permission.plugins.Permission_GroupManager.getPrimaryGroup(Permission_GroupManager.java:327) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
	at me.xeroun.mcmmoextras.McMMOExtras.getMaxSkillLevel(McMMOExtras.java:101) ~[?:?]
	at me.xeroun.mcmmoextras.expbar.ExpBarEvents.lambda$onExpGain$0(ExpBarEvents.java:33) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```
If it's something wrong with a different plugin though, let me know so I can direct this problem to the correct person.

**Comment by TuxCoding** [comment]
What's your version of GroupManager and Vault? Do you reloaded the server before?

**Comment by YaibaToKen** [comment]
Vault: 1.5.6-b49
GroupManager: vGMBuildVer (Phoenix)+1

**Comment by TuxCoding** [comment]
Could you try it with Vault 1.6.

**Comment by YaibaToKen** [comment]
Afraid the latest version i can find is Vault 1.5.6 :/ could you possibly provide me a link? I see it hasn't been updated since 2015
